### ISSUE TITLE
Line wrap does not work on mobile /small screens... sometimes.

### ISSUE THREAD

**Issue by Nikica-Luger** [adrianmcli/react-rotating-text#11]
If you have a narrow screen (e.g. mobile preview on chrome), longer sentences will stop being rendered after the first line, ... _sometimes_.
It stops, the caret goes one line down, but does not render anything. When is resize during that error, the text suddenly appears. So this behaviour is a bit nondeterministic, and i hope you can reproduce it.

**Comment by adrianmcli** [comment]
To be honest, I've been thinking about rewriting this library for a while now. I wrote this quite a long time ago and it definitely isn't as robust as I would like it. In the mean time, I am not sure if I can reproduce the bug you are talking about. Perhaps if you can make a [webpackbin](https://www.webpackbin.com/) example, I can take a look? That being said, I probably don't have much bandwidth to fix anything unless it's relatively minor.

**Comment by Nikica-Luger** [comment]
Hey @adrianmcli , thank you for the fast response! I understand, so  i switched to [typed.js](http://www.mattboldt.com/demos/typed-js/) for the current project, as i need it now. Thank you, nevertheless.
