### ISSUE TITLE
typing interval and deleting interval gets slow on Android

### ISSUE THREAD

**Issue by paolitaclo** [adrianmcli/react-rotating-text#12]
We are using this library for our project in React and we found an issue on mobiles that use Android when we scroll down the page and scroll up again to show the words that use react-rotating-text the typing interval and the deleting interval get slower than before we do the scrolling. 

```
class Home extends Component {
  render() {
    const sportTypes = ['swim', 'tennis', 'soccer', 'basketball'];  
  };
  return (
    <h1 className="title">Let's play <span className="text-orange type-own-line">
    <ReactRotatingText items={sportTypes}/></span></h1>
  );
}
```

Is there any suggestion on how to solve this? Thanks in advance!

**Comment by adrianmcli** [comment]
Hey @paolitaclo thanks for the issue. Unfortunately, I'm not sure if I can reproduce the error.

If nothing else works for you, you might want to consider switching to [typed.js](http://www.mattboldt.com/demos/typed-js/), which others have found to be pretty good.

**Comment by adrianmcli** [comment]
Closed due to inactivity.
