### ISSUE TITLE
New feature? Event Callback functions

### ISSUE THREAD

**Issue by charj** [adrianmcli/react-rotating-text#16]
Great work with this plugin.
I would love a way to listen to events, I've written an example of what I would like to achieve.

```
<ReactRotatingText
    items ={['events', 'would', 'be', 'awesome']}
    onTypingStart={console.log('Typing has started')}
    onTypingEnd={console.log('Typing has finished')}
    onDeletingStart={console.log('Deleting has started')}
    onDeletingEnd={console.log('Deleting has finished')}
/>
```
Could anybody help steer me in the direction of how I would achieve something like this?

My use case is that I would like to update an image `onTypingEnd()`.

Obviously the names of the events can change, it's just an example at this point.

Thanks.

**Comment by adrianmcli** [comment]
To be quite honest, even I don't really recall how I wrote this component. I'm thinking I'm going to do a re-write with RxJS some time in the future. But until then, if anyone else has an idea of where to inject those callback props, that would be great.

**Comment by charj** [comment]
I have some ideas, but there's some weird stuff going on with `props.items`.
Its like the default values `['first',second','third']` are still in use.

Will provide some examples in due course.

**Comment by charj** [comment]
#18
