### ISSUE TITLE
This repository has no license

### ISSUE THREAD

**Issue by dotcs** [adrianmcli/react-rotating-text#24]
Thanks for this awesome package. I've noticed that this repository does not have an open source license yet. Please consider adding a license.

Follow the links to learn more about [how to add a license to a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository), [which licenses are available](https://choosealicense.com/) and [why you should do so](https://medium.com/glitch/why-add-a-license-to-your-open-source-project-6f07941f9288).

Thank you very much in advance for adding a license to your project.

**Comment by adrianmcli** [comment]
It's at the bottom of the README.md.

**Comment by dotcs** [comment]
Thank you @adrianmcli for your quick answer. You're right, the information is there.

To explain why I wrote the ticket: I came here from an automated tool, which is called [license-ls](https://www.npmjs.com/package/license-ls) and does scan licenses by walking through the node modules dependency graph. This package is listed as `unknown` because it does not add license information in the [package.json](https://github.com/adrianmcli/react-rotating-text/blob/master/package.json) and no `LICENSE` file in the project's root directory (not sure if this is tested by the tool).

Large companies typically scan their code bases for legal issues and this is why I found your package. You're a false positive, but still you might consider to also add a license file as described in the link above and also mention this license in the `package.json` file.

Thank you very much for your support and help to maintain the downstream processes. :)

**Comment by dotcs** [comment]
Steps to reproduce:

```bash
cd /path/to/some/dir
npm init -y
npm install --save react-rotating-text
npx license-ls --format=json > deps.json
```

And then run

```console
$ cat deps.json | grep -C 5 react-rotating-text
[
  {
    "id": 0,
    "name": "react-rotating-text",
    "version": "1.4.1",
    "license": "unknown (?)",
    "repository": "git+https://github.com/adrianmc/react-rotating-text.git",
    "author": "Adrian Li",
    "homepage": "https://github.com/adrianmc/react-rotating-text",
    "dependencyLevel": "production"
  },
  {
    "id": 1,
    "name": "classnames",
```

Which shows that `react-rotating-text` is listed with an unknown license.

**Comment by adrianmcli** [comment]
Happy to take a PR for it!
