### ISSUE TITLE
console warnings 

### ISSUE THREAD

**Issue by saniko** [adrianmcli/react-rotating-text#3]
Warning: Unknown props `items`, `deletingInterval`, `emptyPause`, `pause`, `typingInterval` on <span> tag. Remove these props from the element.

I'm using the minimal setup:

import ReactRotatingText from 'react-rotating-text';

<ReactRotatingText items={['first', 'second', 'third']} />

versions:
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "react-rotating-text": "^1.1.2",

**Comment by saniko** [comment]
Any idea?

**Comment by adrianmcli** [comment]
I just published a new version with the fix, thanks for reporting this. Try to `npm install` again to get `v1.1.3` and let me know if this fixes the issue.

**Comment by saniko** [comment]
Thanks,
Issue solved.
