### ISSUE TITLE
Randomize order of items being displayed

### ISSUE THREAD

**Issue by andyngo** [adrianmcli/react-rotating-text#5]
Hi, first of all thank you for the plugin. It's super easy to set up and does not throw errors with SSR unlike a few that I have tried.

Is it possible for us to randomize the order of which the items in the array is displayed? For example: `items={[first, second, third, fourth]}` will randomly be displayed in an order say like: second, fourth, third, first and keeps looping+randomizing.

We can then enable it with a props like `randomize={true}` or something. What do you think?

**Comment by adrianmcli** [comment]
This is actually a great feature request. Unfortunately, it's been a long time since I've worked on this code. At some point I might end up rewriting the entire thing. I'll leave this issue open for now though, since it's nice to have aspirational features available for others to see.

**Comment by harlemfitzgerald** [comment]
First and foremost ... Thank you. I've tried several "type-writer" packages and this one "just works". Your effort is **most** appreciated.

**Comment by charj** [comment]
This has now been done & merged https://github.com/adrianmcli/react-rotating-text/pull/14 @andyngo

**Comment by adrianmcli** [comment]
Should be published now. Can re-open if issue persists.

**Comment by andyngo** [comment]
Oh my, it's been a while. Thank you so much @charj and @adrianmcli!
