### ISSUE TITLE
Elements after using ReactRoatingText component disappear for seconds

### ISSUE THREAD

**Issue by paolitaclo** [adrianmcli/react-rotating-text#8]
I am using this on the app, when I test the app on an iPhone and I scroll down and then scroll up the HTML tag that comes right after this component disappear for seconds and then appears again. but if I implement it, at last, it will work fine.
```<h5>bla bla bla</h5>
  <h1>Become a <span className="text-orange type-own-line">
    <ReactRotatingText items={wordsTypes} /></span></h1>
  <p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem....
  </p>``

**Comment by adrianmcli** [comment]
@paolitaclo can you create an example on webpackbin?

**Comment by adrianmcli** [comment]
Closed due to inactivity, feel free to leave a comment if issue persists.
