### ISSUE TITLE
Doesn't work with React 16

### ISSUE THREAD

**Issue by ozasadnyy** [adrianmcli/react-rotating-text#9]
As PropTypes were moved from react lib, this module started failing
![image](https://user-images.githubusercontent.com/2954281/31448434-1edee262-aead-11e7-9a9a-1fa8953aaa31.png)

**Comment by adrianmcli** [comment]
@ozasadnyy thanks for pointing this out. Do you think you can submit a PR? I've been quite busy lately.

**Comment by adrianmcli** [comment]
@ozasadnyy Can you confirm that the currently re-published version on NPM works with React 16 now? If so, close this issue at your convenience.

**Comment by adrianmcli** [comment]
This should be resolved.
